"use client";

import { Suspense, lazy, useEffect, useState } from "react";
import { BookOpen, Compass, Crosshair, Shield, SlidersHorizontal, Sparkles, Swords, Users, Volume2 } from "lucide-react";
import Image from "next/image";
import project from "../package.json";
import towerCatalog from "../data/tower-stats.json";
import TowerSimulator from "@/components/tower-simulator";
import TowerLibrary from "@/components/tower-library";

const DefenseScene = lazy(() => import("@/components/defense-scene"));

type Tower = (typeof towerCatalog.towers)[number];
const towers = towerCatalog.towers as Tower[];
const rawBuildDate = process.env.NEXT_PUBLIC_BUILD_AT ? new Date(process.env.NEXT_PUBLIC_BUILD_AT) : null;
const buildDate = rawBuildDate && Number.isFinite(rawBuildDate.getTime()) ? rawBuildDate : null;

type Plan = { mode: string; map: string; team: "Solo" | "Co-op"; level: string; confidence: string; opener: string; mid: string; late: string; soloNote: string; source: string; evidence?: { label: string; url: string }[] };
const plans: Plan[] = [
  { mode: "Casual", map: "Any standard map", team: "Solo", level: "Any", confidence: "Community pattern, verify patch", opener: "Place a low-cost defender early; add detection only when the wave table calls for it.", mid: "Keep an emergency reserve instead of maxing every tower. Add economy only if the map and remaining waves repay it.", late: "Concentrate upgraded damage around the longest shared path. Keep one answer for the final boss and an escape plan for leaks.", soloNote: "Solo has no partner to cover a missed detection type or rescue a late economy choice. Test the wave preview before spending.", source: "https://tds.wiki/w/Casual_Mode" },
  { mode: "Easy", map: "Any standard map", team: "Solo", level: "Any", confidence: "Community pattern, verify patch", opener: "Use one inexpensive tower to stabilize the opening waves.", mid: "Delay optional support until core damage is paid for; avoid spreading upgrades across too many placements.", late: "Build toward a reliable boss answer before the last stretch. Easy Mode is listed as 20 waves in the current mode research.", soloNote: "A short mode rewards a lean plan. Extra economy can lose value if bought too late.", source: "https://tds.wiki/w/Easy_Mode" },
  { mode: "Intermediate", map: "Any standard map", team: "Solo", level: "5", confidence: "Community pattern, verify patch", opener: "Cover early waves with a cheap attacker; preserve cash for the first pressure spike.", mid: "Mix range and damage rather than relying on one placement lane. Track Patient Zero timing from the current wave page.", late: "Upgrade your strongest boss damage and retain crowd coverage for summoned enemies.", soloNote: "Plan the final boss and its adds as two jobs. A single-target setup may need a second crowd answer.", source: "https://tds.wiki/w/Intermediate_Mode" },
  { mode: "Molten", map: "Any standard map", team: "Solo", level: "15", confidence: "Creator two-tower clear reported", opener: "A July 2026 creator guide reports a solo clear using Shotgunner and Minigunner, with no skill tree or special towers. Treat those as the reported loadout, not a guaranteed current build order.", mid: "Keep the early defense affordable, then build toward Minigunner damage without letting the short mode's economy arrive too late to use.", late: "Reserve a clear answer for Molten Boss and verify the current boss traits before copying a counter. Record the map and game version when reproducing the two-tower report.", soloNote: "The official wiki's Index also lists solo Molten triumph badges. The creator video is a stronger solo guide lead than a generic checklist, but its route has not been independently replayed against this snapshot.", source: "https://tds.wiki/w/Molten_Mode", evidence: [{ label: "PufferSquishy solo Molten, 2 towers, no skill tree, Jul 22 2026", url: "https://www.youtube.com/watch?v=sLq2LsoJZqw" }, { label: "Official wiki solo triumph badges", url: "https://tds.wiki/w/Index" }] },
  { mode: "Fallen", map: "Any standard map", team: "Solo", level: "30", confidence: "Creator solo guides reported", opener: "A February creator guide reports a two-tower solo clear with a wave-by-wave video outline; it calls Shotgunner the early answer and Minigunner the late damage option.", mid: "A June 2026 guide outline starts with Crook Boss/Militant and calls out the wave 30–39 stretch. Protect an economy reserve and prioritize the next pressure spike over maxing support early.", late: "Keep boss damage concentrated and crowd coverage available for the surrounding enemies. Treat both videos as reported routes, not proof that their exact loadouts remain current.", soloNote: "Solo Fallen is supported by official solo badge entries. Community routes vary by map, tower ownership, and consumables; the linked videos provide leads for replayable testing, not a universal build.", source: "https://tds.wiki/w/Fallen_Mode", evidence: [{ label: "Cbx Games solo Fallen guide, Jun 13 2026", url: "https://www.youtube.com/watch?v=PP_ytYoirmI" }, { label: "SebasDark25 solo Fallen, two tower slots, Feb 18 2026", url: "https://www.youtube.com/watch?v=bIWS0hmINVM" }, { label: "Official wiki solo triumph badges", url: "https://tds.wiki/w/Index" }] },
  { mode: "Frost", map: "Any standard map", team: "Solo", level: "60 · 40 waves", confidence: "Creator solo clears reported", opener: "Keep the first purchases lean and confirm the active wave order and detection requirements before committing to a narrow tower choice.", mid: "The wiki places Frost Champion at wave 33 and Frost Spirit at wave 40. Budget for the boss and its adds as separate jobs.", late: "Use only counters that work against the current boss traits; keep a fallback damage route and do not treat a video title as a copy-ready wave build.", soloNote: "Two creator videos document solo Frost clears with different constraints, one with Turret and one titled no special towers/no skill tree. The exact route still needs a version-matched run log.", source: "https://tds.wiki/w/Frost_Mode", evidence: [{ label: "ZowserTDS solo Frost with Turret, Apr 3 2026", url: "https://www.youtube.com/watch?v=EnY8X3VTLHg" }, { label: "ZowserTDS solo Frost, no special towers/no skill tree, Jul 2 2026", url: "https://www.youtube.com/watch?v=NT7RDS_Hyfc" }] },
  { mode: "Hardcore", map: "Any Hardcore map", team: "Solo", level: "50 · 45 waves", confidence: "Community route reported, patch-sensitive", opener: "Read the current Hardcore cash and wave rules first. The mode research notes no periodic cash drops, so avoid an opener that assumes passive income.", mid: "One community report describes Farm, Engineer, Commander, DJ, and Golden Minigunner with a near-max skill tree and active micro. Treat that as a loadout report, not a guaranteed route.", late: "Plan the Void Reaver fight and micro before the final waves; preserve a recovery budget for the actual boss abilities.", soloNote: "Solo Hardcore claims vary by tower ownership, map, skill tree, and micro. The linked report is anecdotal and does not establish a universal build order.", source: "https://tds.wiki/w/Hardcore_Mode", evidence: [{ label: "Community discussion of solo/duo Hardcore, Jun 29 2026", url: "https://www.reddit.com/r/TowerDefenseSimulator/comments/1uig1hi/is_it_possible_to_beat_hardcore_soloduo/" }] },
  { mode: "Voidcore", map: "Any Voidcore map", team: "Solo", level: "Hardcore triumph · 50 waves", confidence: "Conflicting community claims", opener: "Check current consumable and skill restrictions before the match. Wiki mode notes say skills and consumables are disabled.", mid: "Reserve budget for Shrines from wave 11 and the repeating late-wave pressure. A co-op cash plan does not transfer to a solo run.", late: "Plan boss damage, adds, and ability responses separately. A solo claim without the exact loadout, map, update, and wave log is not a reproducible strategy.", soloNote: "Community reports conflict: June discussions call solo impossible, while later posts claim a solo clear. The linked posts do not establish one consistent repeatable method, so this remains experimental.", source: "https://tds.wiki/w/Voidcore", evidence: [{ label: "June 2026 solo Voidcore discussion", url: "https://www.reddit.com/r/TowerDefenseSimulator/comments/1u61e17/how_are_people_soloing_voidcore/" }, { label: "August 2026 claimed solo Voidcore method", url: "https://www.reddit.com/r/TDS_Roblox/comments/1vjjqom/solo_voidcore_has_been_possible_this_whole_time_we_have_all_been_fooled/" }] },
  { mode: "Challenge Trials", map: "Rotating challenge map", team: "Solo", level: "40", confidence: "Needs current trial verification", opener: "Read the active modifiers and map before selecting towers; yesterday's trial plan may no longer apply.", mid: "Adapt the core to bans, cash rules, and enemy traits in the active trial.", late: "Keep a flexible reserve for the final modifier interaction and boss.", soloNote: "A solo trial run must be labeled with its exact rotation and date. Rotation-specific notes expire when the trial changes.", source: "https://tds.wiki/w/Challenge_Trials" },
  { mode: "PVP", map: "Current arena", team: "Solo", level: "25", confidence: "Rules summary, tactics unverified", opener: "Confirm whether the current queue is 1v1 or 2v2 and review ranked bans.", mid: "Balance defense with sending pressure; do not spend all resources on waves your opponent can answer.", late: "Keep a defensive buffer and send only when your own lane is stable.", soloNote: "In 1v1, you own both defense and send timing. In 2v2, coordinate roles with the teammate instead of applying this solo note.", source: "https://tds.wiki/w/PvP" },
  { mode: "Pizza Party", map: "Pizza Party", team: "Solo", level: "Unlock required · special waves", confidence: "Creator solo triumph reported", opener: "A January 2026 creator video reports a solo triumph using Spotlight Technician. Check the current loadout, grid placement rules, and enemy wave list before adapting that clear.", mid: "The wiki strategy notes 20% enemy defense; prioritize defense-melting coverage and an answer to flying enemies rather than spreading upgrades evenly.", late: "Keep Wox the Fox's boss pressure and its scared effect in the plan. The source page gives counters, while the video title supports a solo-clear report, not a current wave-by-wave guarantee.", soloNote: "The official wiki lists a solo Pizza Party triumph badge. Keep the creator's Spotlight Technician report linked separately from wiki mechanics and verify it against the current rules.", source: "https://tds.wiki/w/Pizza_Party", evidence: [{ label: "ZowserTDS solo Pizza Party with Spotlight Technician, Jan 13 2026", url: "https://www.youtube.com/watch?v=COlO7GzVvEU" }, { label: "Official wiki solo triumph badges", url: "https://tds.wiki/w/Index" }] },
  { mode: "Badlands II", map: "Badlands II", team: "Solo", level: "25 · 30 waves", confidence: "Official solo badge; route unverified", opener: "Badlands II duplicates enemies across three paths. Use central overlap where the measured path geometry allows; early towers still need to cover separate entrances.", mid: "Solo receives the full enemy cash allocation, but the All Paths modifier means enemy traffic is tripled and Mutation raises HP over time. Favor area coverage and avoid assuming a co-op lane split.", late: "Save enough damage for the fast Gunslinger on wave 30 and account for HP Locked base health. The official page recommends high-DPS, area damage, and support; no wave-by-wave solo build is certified here.", soloNote: "The Official Index lists the Outlaw solo triumph badge. The map's three-path duplication and solo cash rules make this a distinct plan, not a standard Fallen build.", source: "https://tds.wiki/w/Badlands_II", evidence: [{ label: "Official Badlands II page and Outlaw solo badge", url: "https://tds.wiki/w/Badlands_II" }] },
  { mode: "Polluted Wasteland II", map: "Polluted Wasteland II", team: "Solo", level: "Unlock required", confidence: "Official solo badge; route unverified", opener: "The Official Index lists The Cure for a Polluted Wasteland II solo triumph, so solo completion is documented. Confirm current matchmaking and map rules before planning the run.", mid: "Use the mode's own wave and enemy tables; standard survival economy advice does not transfer automatically.", late: "Plan boss damage and any adds as separate jobs. The solo badge supports availability, but a reproducible current loadout and wave sequence are still missing.", soloNote: "A June 2026 discussion questioned solo availability, but the official solo triumph entry is stronger evidence that a solo clear exists. The exact route remains unverified.", source: "https://tds.wiki/w/Polluted_Wasteland_II", evidence: [{ label: "Official wiki solo triumph badge", url: "https://tds.wiki/w/Index" }, { label: "Community solo-availability discussion, Jun 22 2026", url: "https://www.reddit.com/r/TDS_Roblox/comments/1ucv8qt/is_there_any_hope_for_a_solo/" }] },
  { mode: "Story Mode", map: "Current chapter", team: "Solo", level: "Chapter requirements", confidence: "New mode, verify chapter update", opener: "Read the chapter objective and enemy list; objectives can change what counts as a successful clear.", mid: "Spend around the objective instead of applying survival-mode economy assumptions.", late: "Keep a counter for chapter-specific boss mechanics and confirm completion conditions.", soloNote: "Label chapter and version. Story chapters may have unique rules that make a generic solo tier list misleading.", source: "https://tds.wiki/w/Story_Mode" },
  { mode: "Casual", map: "Any standard map", team: "Co-op", level: "Any", confidence: "Community pattern, verify patch", opener: "Agree who covers the first lane and who is saving for economy.", mid: "Split roles only after agreeing on cash sharing and detection coverage.", late: "Concentrate boss damage and keep a second player able to answer adds.", soloNote: "Co-op assumptions: role split and shared coverage.", source: "https://tds.wiki/w/Casual_Mode" },
];

const modes = ["Casual", "Easy", "Intermediate", "Molten", "Fallen", "Frost", "Hardcore", "Voidcore", "Challenge Trials", "PVP", "Pizza Party", "Badlands II", "Polluted Wasteland II", "Story Mode"];

export default function StrategyLab() {
  const [mode, setMode] = useState("Frost");
  const [team, setTeam] = useState<"Solo" | "Co-op">("Solo");
  const [selectedMap, setSelectedMap] = useState("Mode default");
  const [activeTab, setActiveTab] = useState("Strategy");
  const [speaking, setSpeaking] = useState(false);
  const plan = plans.find((item) => item.mode === mode && item.team === team) ?? { mode, map: "Mode-specific map", team: "Co-op" as const, level: "Varies", confidence: "No reviewed co-op strategy", opener: "No reviewed team-specific opener is recorded for this mode yet.", mid: "Do not apply the solo plan as a team strategy. Agree on lane, cash, and tower responsibilities before the run.", late: "No reviewed team-specific boss plan is recorded for this mode yet.", soloNote: "No verified team-specific report is available for this mode.", source: "https://tds.wiki/w/Gamemodes" };
  function readStrategyAloud() {
    if (!window.speechSynthesis) return;
    if (speaking) { window.speechSynthesis.cancel(); setSpeaking(false); return; }
    const utterance = new SpeechSynthesisUtterance(`${plan.team} ${plan.mode} plan. Opening: ${plan.opener} Mid-game: ${plan.mid} Boss preparation: ${plan.late}`);
    utterance.onend = () => setSpeaking(false);
    utterance.onerror = () => setSpeaking(false);
    setSpeaking(true);
    window.speechSynthesis.speak(utterance);
  }
  const buildZone = Intl.DateTimeFormat().resolvedOptions().timeZone || "local timezone unavailable";
  const [localBuildStamp, setLocalBuildStamp] = useState<string | null>(null);
  useEffect(() => {
    if (buildDate && Number.isFinite(buildDate.getTime())) {
      const timer = window.setTimeout(() => setLocalBuildStamp(new Intl.DateTimeFormat(undefined, { year: "numeric", month: "short", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false, timeZoneName: "long" }).format(buildDate)), 0);
      return () => window.clearTimeout(timer);
    }
  }, []);

  return <main className="app-shell">
    <header className="topbar">
      <a className="brand" href="#home" aria-label="TDS Strategy Lab home"><Image className="brand-icon" src="/tds-mark.svg" alt="" width={38} height={38} unoptimized/><span><strong>TDS <i>STRATEGY LAB</i></strong><small>FIELD GUIDE · RESEARCH CUTOFF 2026-09-26</small><small className="version-stamp">Version {project.version} · Updated {localBuildStamp ?? (buildDate ? `${buildDate.toISOString().replace("T", " ").replace("Z", " UTC")}` : "time unavailable")} · {localBuildStamp ? buildZone : "build time in UTC"}</small></span></a>
      <nav className="primary-nav" aria-label="Main navigation">{["Strategy", "Towers", "Modes", "Encyclopedia"].map((tab) => <a key={tab} className={activeTab === tab ? "nav-link selected" : "nav-link"} href={tab === "Encyclopedia" ? "/encyclopedia" : tab === "Towers" ? "#towers" : tab === "Modes" ? "#mode-plans" : "#planner"} onClick={() => setActiveTab(tab)}>{tab}</a>)}</nav>
      <div className="top-actions"><button className="icon-button" type="button" aria-label={speaking ? "Stop reading the strategy aloud" : "Read the selected strategy aloud"} aria-pressed={speaking} title={speaking ? "Stop reading" : "Read strategy aloud"} onClick={readStrategyAloud}><Volume2 size={18}/></button><span className="profile-button" aria-label="Current view: Guide mode" title="Current view">GUIDE MODE</span></div>
    </header>
    <div className="layout">
      <aside className="rail" aria-label="Guide sections"><p className="eyebrow">PLAYBOOK</p><a className="rail-link active" href="#planner"><Compass size={17}/>Strategy lab</a><a className="rail-link" href="#simulator"><SlidersHorizontal size={17}/>Tower simulator</a><a className="rail-link" href="#mode-plans"><Swords size={17}/>Mode plans</a><a className="rail-link" href="#sources"><BookOpen size={17}/>Sources</a><div className="rail-note"><span className="status-dot"/> Research snapshot <b>Sep 26, 2026</b><small>Community strategies are labeled separately from verified game data.</small></div></aside>
      <section className="workspace" id="home">
        <div className="hero-grid" id="planner">
          <div className="hero-copy"><div className="eyebrow accent"><Sparkles size={14}/>TACTICAL RESEARCH DESK</div><h1>Plan the run.<br/><em>Own every wave.</em></h1><p>Explore tower stats, map the defense, and build a strategy around your mode, player count, and current assumptions.</p><div className="hero-stats"><span><b>14</b> MODE PATHS</span><span><b>SOLO</b> FIRST-CLASS PLANS</span><span><b>3D</b> INTERACTIVE SCENE</span></div></div>
          <div className="scene-card"><div className="scene-head"><span><i className="live-dot"/> DEFENSE OVERVIEW</span><span>INTERACTIVE 3D <span className="scene-kbd">DRAG TO ORBIT</span></span></div><Suspense fallback={<div className="scene-fallback" role="status">Loading the interactive defense view. The tower stats and mode planner remain available.</div>}><DefenseScene/></Suspense><div className="scene-legend"><span><i className="legend-tower"/> Towers</span><span><i className="legend-path"/> Enemy path</span><span className="scene-state">● 3D SCENE PREVIEW</span></div></div>
        </div>

        <div className="planner-bar"><div className="planner-title"><div className="planner-icon"><Crosshair size={19}/></div><div><strong>Run planner</strong><small>Solo is planned separately from co-op. PvP solo means 1v1.</small></div></div><label className="field-label">MODE<select value={mode} onChange={(e) => setMode(e.target.value)}>{modes.map((item) => <option key={item}>{item}</option>)}</select></label><fieldset className="team-switch"><legend>TEAM SIZE</legend><button type="button" aria-pressed={team === "Solo"} className={team === "Solo" ? "choice active" : "choice"} onClick={() => setTeam("Solo")}><Crosshair size={14}/>Solo</button><button type="button" aria-pressed={team === "Co-op"} className={team === "Co-op" ? "choice active" : "choice"} onClick={() => setTeam("Co-op")}><Users size={14}/>Co-op</button></fieldset><label className="field-label map-select">MAP<select value={selectedMap} onChange={(event) => setSelectedMap(event.target.value)}><option>Mode default</option><option>Gilded Path</option><option>U-Turn</option><option>Forest Camp</option><option>Derelict Outpost</option><option>Unknown Garden</option><option>Wretched Front</option><option>Outskirts Commune</option><option>Space City</option></select></label><button className="run-button" onClick={() => document.getElementById("mode-plans")?.scrollIntoView({ behavior: "smooth" })}>View plan <span>↗</span></button></div>

        <div className="content-grid">
          <section className="card strategy-card" id="mode-plans"><div className="section-heading"><div><span className="eyebrow">FIELD NOTES / {mode.toUpperCase()}</span><h2>{team} {mode} plan</h2></div><span className="confidence">{plan.confidence}</span></div><div className="plan-meta"><span>◉ {selectedMap === "Mode default" ? plan.map : selectedMap}</span><span>◈ Level: {plan.level}</span><a href={plan.source} target="_blank" rel="noreferrer">Wiki source ↗</a></div><div className="phase-list"><article><span className="phase-num">01</span><div><h3>Opening economy</h3><p>{plan.opener}</p></div></article><article><span className="phase-num">02</span><div><h3>Mid-game build</h3><p>{plan.mid}</p></div></article><article><span className="phase-num">03</span><div><h3>Boss preparation</h3><p>{plan.late}</p></div></article></div><div className="solo-callout"><span className="solo-mark">{team === "Solo" ? "S" : "↔"}</span><div><strong>{team === "Solo" ? "Solo constraint" : "Team assumption"}</strong><p>{plan.soloNote}</p></div></div><div className="strategy-foot"><span>{selectedMap === "Mode default" ? "General route advice. No map-specific placement proof." : `Map selected: ${selectedMap}. Placement geometry has not been verified.`}</span><div className="plan-evidence">{plan.evidence?.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</div><button onClick={() => navigator.clipboard?.writeText(`${team} ${mode}: ${plan.opener} ${plan.mid} ${plan.late}`)}>Copy build notes</button></div></section>

          <TowerSimulator towers={towers} />
        </div>

        <TowerLibrary towers={towers} />

        <section className="source-strip" id="sources"><Shield size={20}/><div><strong>Research with receipts</strong><p>Every imported article will retain source title, revision, history, license, and adaptation details. Community tactics stay labeled as reports, especially where solo clears conflict.</p></div><a href="https://tds.wiki/w/Tower_Defense_Simulator_Wiki:Copyrights" target="_blank" rel="noreferrer">Content policy ↗</a></section>
        <footer><span>TDS STRATEGY LAB · INDEPENDENT FAN RESOURCE</span><span>Research snapshot: 2026-09-26 · Source data is still being verified</span></footer>
      </section>
    </div>
  </main>;
}
